<a href="https://colab.research.google.com/github/vvalcristina/datascience_codenation/blob/master/Codenation_Tensor_Flow_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Flow 2.0**

In [1]:
!pip uninstall -y tensorflow

In [2]:
!pip install tensorflow-gpu==2.0.0

In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0'

**Constantes**

Definindo as constantes

In [0]:
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [7]:
#Verificando as dimensões
tensor_20.shape

TensorShape([2, 2])

**Acessando as variáveis constantes**

Utilizando o numpy para inicializar

In [8]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

Convertendo um array para Tensor Flow

In [0]:
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

**Variáveis**

Definindo as variáveis

In [17]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Acessando os valores dessas variáveis

In [18]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [19]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

**Operações matemáticas com Tensor Flow**

In [20]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
#Soma escalar
tensor + 2

<tf.Tensor: id=45, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [22]:
#Multiplicação escalar
tensor * 5

<tf.Tensor: id=47, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

**Utilizando funções nativas do Tensor Flow**

In [23]:
tensor

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [25]:
#Add
tf.add (tensor,tensor_20)

<tf.Tensor: id=48, shape=(2, 2), dtype=int32, numpy=
array([[24,  6],
       [35, 55]], dtype=int32)>

In [26]:
#Subtract
tf.subtract (tensor, tensor_20)

<tf.Tensor: id=49, shape=(2, 2), dtype=int32, numpy=
array([[-22,  -2],
       [-29, -47]], dtype=int32)>

In [27]:
#Multiply
tf.multiply (tensor, tensor_20)

<tf.Tensor: id=50, shape=(2, 2), dtype=int32, numpy=
array([[ 23,   8],
       [ 96, 204]], dtype=int32)>

**Utilizando funções do Numpy com Tensor Flow**

In [28]:
# Squaring
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [29]:
# Squareroot
np.sqrt(tensor)


array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [30]:
#Add
np.add(tensor, tensor_20)

array([[24,  6],
       [35, 55]], dtype=int32)

In [31]:
#Subtract
np.subtract(tensor, tensor_20)

array([[-22,  -2],
       [-29, -47]], dtype=int32)

In [32]:
#Division
np.divide(tensor, tensor_20)

array([[0.04347826, 0.5       ],
       [0.09375   , 0.07843137]])

In [33]:
#Multiply
np.multiply(tensor, tensor_20)

array([[ 23,   8],
       [ 96, 204]], dtype=int32)

**Dot product**

In [34]:
tensor

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [35]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [36]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [37]:
tf.add (tensor,tensor_20)

<tf.Tensor: id=51, shape=(2, 2), dtype=int32, numpy=
array([[24,  6],
       [35, 55]], dtype=int32)>

**Strings Tensor Flow 2.0**

In [38]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=52, shape=(), dtype=string, numpy=b'TensorFlow'>

* Operações com String

In [39]:
tf.strings.length(tf_string)

<tf.Tensor: id=53, shape=(), dtype=int32, numpy=10>

In [40]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=57, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

**Arrays de String**

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [42]:
tf_string_array

<tf.Tensor: id=58, shape=(3,), dtype=string, numpy=array([b'TensorFlow', b'Deep Learning', b'AI'], dtype=object)>

**Iteração com Strings**

In [43]:
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
